### PR TITLE
added TabView and fixed white background when in dark color scheme for issue #10

### LINKED ISSUE #10: Adding bottom tab bar for page access
Adding tabView to the bottom of HomePage with:
1. Dashboard
2. Exercises
3. Stats
4. Profile

### PR DESCRIPTION
**Pull request by arota18**
I've added a .swift file for every tab inside the TabView so the project will stay easily maintainable in the future.
I've noticed too that when in dark mode the background remains white so I've added a property for that.

Screenshot 2023-07-12 alle 22 54 47

tbh I'm not sure about this file (SwiftJym.xcodeproj/project.pbxproj), do you know if it should be ignored or committed?

As you can see most of the changes in SwiftJym/JymHomePage.swift are simply indentation as a result of adding the tabview.

### CODE REVIEW

File: SwiftJym/Exercise.swift [hunk 1]
```diff
@@ -1,5 +1,5 @@
 //
-//  Excercise.swift
+//  Exercise.swift
```
Comment (arota18) [inline SwiftJym/Exercise.swift:2]: corrected typo from the last commit

**Review by soaapp — APPROVED** [review]
Reviewed + tested changes in branch
